
export const navLinks = [
  {
    title: 'HOMBRES',
    href: '/hombres',
    sublinks: [
      {
        title: 'Playeras',
        href: '/hombres/playeras',
        sublinks: [{ title: 'Tanks', href: '/hombres/playeras/tanks' }],
      },
      { title: 'Shorts', href: '/hombres/shorts' },
      { title: 'Pantalones', href: '/hombres/pantalones' },
      { title: 'Sudaderas', href: '/hombres/sudaderas' },
      { title: 'Chamarras', href: '/hombres/chamarras' },
      { title: 'Ver Todo', href: '/hombres' },
    ],
  },
  {
    title: 'MUJERES',
    href: '/mujeres',
    sublinks: [
      {
        title: 'Blusas',
        href: '/mujeres/blusas',
        sublinks: [
          { title: 'Tops', href: '/mujeres/tops' },
          { title: 'Bras Deportivos', href: '/mujeres/bras-deportivos' },
        ],
      },
      {
        title: 'Leggings',
        href: '/mujeres/leggings',
        sublinks: [{ title: 'Shorts', href: '/mujeres/shorts' }],
      },
      {
        title: 'Sudaderas',
        href: '/mujeres/sudaderas',
        sublinks: [{ title: 'Chamarras', href: '/mujeres/chamarras' }],
      },
      { title: 'Ver Todo', href: '/mujeres' },
    ],
  },
  {
    title: 'ACCESORIOS',
    href: '/accesorios',
    sublinks: [
      {
        title: 'Pachones y Shakers',
        href: '/accesorios/pachones-shakers',
        sublinks: [
          { title: 'Pachones', href: '/accesorios/pachones' },
          { title: 'Shakers', href: '/accesorios/shakers' },
        ],
      },
      { title: 'Equipo de Entrenamiento', href: '/accesorios/equipo' },
      { title: 'Gorras', href: '/accesorios/gorras' },
      {
        title: 'Mochilas y Maletas',
        href: '/accesorios/mochilas-maletas',
        sublinks: [
          { title: 'Mochilas', href: '/accesorios/mochilas' },
          { title: 'Maletas', href: '/accesorios/maletas' },
        ],
      },
      { title: 'Calcetines', href: '/accesorios/calcetines' },
      { title: 'Ver Todo', href: '/accesorios' },
    ],
  },
  {
    title: 'SUPLEMENTOS',
    href: '/suplementos',
    sublinks: [
      { title: 'Proteínas', href: '/suplementos/proteinas' },
      { title: 'Creatinas', href: '/suplementos/creatinas' },
      { title: 'Pre Entrenos', href: '/suplementos/pre-entrenos' },
      { title: 'Aminoácidos', href: '/suplementos/aminoacidos' },
      { title: 'L-Carnitina', href: '/suplementos/l-carnitina' },
      { title: 'Ver Todo', href: '/suplementos' },
    ],
  },
  {
    title: 'JOYERIA',
    href: '/joyeria',
    sublinks: [{ title: 'Rgmnt', href: '/joyeria/rgmnt' }],
  },
  {
    title: 'MARCAS',
    href: '/marcas',
    sublinks: [
      { title: 'YoungLA', href: '/marcas/youngla' },
      { title: 'Gymshark', href: '/marcas/gymshark' },
      { title: 'Darc Sport', href: '/marcas/darc-sport' },
      { title: 'Vanquish', href: '/marcas/vanquish' },
      { title: 'Dragon Pharma', href: '/marcas/dragon-pharma' },
      { title: 'RAW', href: '/marcas/raw' },
      { title: 'RGMNT', href: '/marcas/rgmnt' },
      { title: 'C4 Energy', href: '/marcas/c4-energy' },
      { title: 'Civil Regime', href: '/marcas/civil-regime' },
      { title: 'Ver Todo', href: '/marcas' },
    ],
  },
];

export type ProductOption = {
  value: string;
  stock: number;
};

export type Product = {
  id: number;
  name: string;
  price: string;
  availability: string;
  images: { src: string; alt: string; dataAiHint: string; option: string }[];
  options: { type: string; values: ProductOption[] };
  description: string;
  gender: 'hombre' | 'mujer' | 'unisex';
  category: 'ropa' | 'suplemento' | 'accesorio' | 'joyeria';
  subcategory: string;
  brand: string;
  // Ropa
  fabric_type?: string;
  is_compression?: boolean;
  // Suplemento
  benefits?: string;
  servings_info?: string;
};

export const products: Product[] = [
  {
    id: 1,
    name: 'Superhero Compression Tees Red',
    price: 'Q.450.00',
    availability: 'Disponible',
    description: 'Conviértete en un héroe del gimnasio con esta playera de compresión. Diseñada para un rendimiento máximo y un estilo inigualable, te ayudará a superar tus límites.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'YoungLA',
    fabric_type: '88% Polyester, 12% Spandex',
    is_compression: true,
    images: [
      {
        src: "/assets/images/marcas/youngla/hombre/superheroeroja.png",
        alt: 'Red compression shirt front',
        dataAiHint: 'red shirt',
        option: 'S',
      },
       {
        src: "/assets/images/marcas/youngla/hombre/superherojarojaatras.png",
        alt: 'Red compression shirt back',
        dataAiHint: 'red shirt man',
        option: 'S',
      },
    ],
    options: {
      type: 'talla',
      values: [
        { value: 'S', stock: 1 },
        { value: 'M', stock: 0 },
        { value: 'L', stock: 0 },
      ],
    },
  },
  {
    id: 2,
    name: 'Warrior Compression Tees Blue',
    price: 'Q.500.00',
    availability: 'Disponible',
    description: 'Desata al guerrero que llevas dentro. Esta playera de compresión azul ofrece un soporte muscular superior y una transpirabilidad excepcional para los entrenamientos más intensos.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'YoungLA',
    fabric_type: '90% Nylon, 10% Elastane',
    is_compression: true,
    images: [
      {
        src:  "/assets/images/marcas/youngla/hombre/warriorazul.png",
        alt: 'Blue compression shirt',
        dataAiHint: 'blue shirt',
        option: 'S',
      },
    ],
    options: {
      type: 'talla',
      values: [
        { value: 'S', stock: 1 },
        { value: 'M', stock: 2 },
        { value: 'L', stock: 3 },
      ],
    },
  },
  {
    id: 3,
    name: 'Onyx 5.0 Seamless T-Shirt in Black/Onyx Grey',
    price: 'Q.450.00',
    availability: 'Disponible',
    description: 'Experimenta la tecnología sin costuras con la Onyx 5.0. Diseñada para un máximo confort y un rendimiento sin restricciones, esta camiseta es perfecta para cualquier tipo de entrenamiento.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'Gymshark',
    fabric_type: '64% Nylon, 28% Polyester, 8% Elastane',
    is_compression: false,
    images: [
      {
        src: "/assets/images/marcas/gymshark/hombre/onyxnegra.jpg",
        alt: 'Onyx Seamless T-Shirt',
        dataAiHint: 'black shirt',
        option: 'M',
      },
    ],
    options: {
      type: 'talla',
      values: [
        { value: 'S', stock: 1 },
        { value: 'M', stock: 2 },
        { value: 'L', stock: 3 },
      ],
    },
  },
  {
    id: 4,
    name: 'Power T-Shirt Black and Red',
    price: 'Q.450.00',
    availability: 'Disponible',
    description: 'Potencia y estilo se unen en esta T-Shirt. Con un ajuste atlético y un diseño audaz en negro y rojo, es la prenda perfecta tanto para dentro como para fuera del gimnasio.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'Gymshark',
    fabric_type: '95% Algodón, 5% Elastano',
    is_compression: false,
    images: [
      {
        src: "/assets/images/marcas/gymshark/hombre/GYMSPOWERNR.png",
        alt: 'Black and red t-shirt',
        dataAiHint: 'black red shirt',
        option: 'S',
      },
    ],
    options: {
      type: 'talla',
      values: [
        { value: 'S', stock: 1 },
        { value: 'M', stock: 2 },
        { value: 'L', stock: 3 },
      ],
    },
  },
  {
    id: 5,
    name: 'Vital Seamless Crop Top Green',
    price: 'Q.450.00',
    availability: 'Disponible',
    description: 'El crop top que lo tiene todo: tecnología sin costuras para una comodidad máxima, tejido que absorbe el sudor y un diseño que realza tu figura.',
    gender: 'mujer',
    category: 'ropa',
    subcategory: 'top',
    brand: 'Gymshark',
    fabric_type: '96% Nylon, 4% Elastane',
    is_compression: true,
    images: [
      {
        src: "/assets/images/marcas/gymshark/mujer/anabelgyms.jpg",
        alt: 'Green crop top',
        dataAiHint: 'green crop top',
        option: 'S',
      },
    ],
    options: {
      type: 'talla',
      values: [
        { value: 'S', stock: 1 },
        { value: 'M', stock: 2 },
        { value: 'L', stock: 3 },
      ],
    },
  },
  {
    id: 6,
    name: 'Core Hourglass Bra Tank Red',
    price: 'Q.450.00',
    availability: 'Disponible',
    description: 'Diseñado para esculpir y dar soporte, este bra tank en un vibrante color rojo es tan funcional como favorecedor. Su diseño de reloj de arena realza tus curvas naturales.',
    gender: 'mujer',
    category: 'ropa',
    subcategory: 'bra-deportivo',
    brand: 'YoungLA',
    fabric_type: '78% Nylon, 22% Elastane',
    is_compression: true,
    images: [
      {
        src: "/assets/images/marcas/youngla/mujer/brarojoyla.png",
        alt: 'Red bra tank',
        dataAiHint: 'red bra',
        option: 'S',
      },
    ],
    options: {
      type: 'talla',
      values: [
        { value: 'S', stock: 1 },
        { value: 'M', stock: 2 },
        { value: 'L', stock: 3 },
      ],
    },
  },
  {
    id: 7,
    name: 'Proteína ISO Dragon Pharma - 2lb',
    price: 'Q.450.00',
    availability: 'Disponible',
    description: 'Isolat de proteína de suero de leche de la más alta pureza para una recuperación muscular óptima. Baja en carbohidratos y grasas, perfecta para definir.',
    gender: 'unisex',
    category: 'suplemento',
    subcategory: 'proteina',
    brand: 'Dragon Pharma',
    benefits: 'Recuperación muscular rápida, bajo en carbohidratos y grasas.',
    servings_info: 'Aproximadamente 30 servicios por envase.',
    images: [
      {
        src: "/assets/images/marcas/dragonpharma/isoproteinblb.png",
        alt: 'Blueberry protein powder',
        dataAiHint: 'protein powder',
        option: 'Blueberry',
      },
      {
        src: "/assets/images/marcas/dragonpharma/proteinachb.png",
        alt: 'White chocolate protein powder',
        dataAiHint: 'protein powder',
        option: 'ChocolateBlanco',
      },
    ],
    options: {
      type: 'sabor',
      values: [
        { value: 'Blueberry', stock: 1 },
        { value: 'ChocolateBlanco', stock: 3 },
      ],
    },
  },
  {
    id: 8,
    name: 'Creatina Monohidratada Dragon Pharma',
    price: 'Q.450.00',
    availability: 'Disponible',
    description: 'Aumenta tu fuerza, potencia y rendimiento con creatina monohidratada micronizada de alta calidad. Un suplemento esencial para cualquier atleta serio.',
    gender: 'unisex',
    category: 'suplemento',
    subcategory: 'creatina',
    brand: 'Dragon Pharma',
    benefits: 'Aumento de fuerza, mejora del rendimiento, mayor volumen muscular.',
    servings_info: 'Disponible en 60 o 200 servicios.',
    images: [
      {
        src: "/assets/images/marcas/dragonpharma/creatinaDP.png",
        alt: 'Creatine container',
        dataAiHint: 'creatine powder',
        option: 'Serv60',
      },
    ],
    options: {
      type: 'servicios',
      values: [
        { value: 'Serv60', stock: 1 },
        { value: 'Serv200', stock: 3 },
      ],
    },
  },
  {
    id: 100,
    name: 'Performance Shorts',
    price: 'Q.350.00',
    availability: 'Disponible',
    description: 'Shorts deportivos de alto rendimiento, ideales para cualquier tipo de entrenamiento. Ligeros y transpirables.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'short',
    brand: 'YoungLA',
    fabric_type: '90% Polyester, 10% Spandex',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/youngla/hombre/shorts/short-performance.png', alt: 'Performance Shorts', dataAiHint: 'men shorts', option: 'M' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 5 }, { value: 'M', stock: 5 }, { value: 'L', stock: 5 }] },
  },
  {
    id: 200,
    name: 'Tech Joggers',
    price: 'Q.550.00',
    availability: 'Disponible',
    description: 'Pantalones jogger con tejido técnico, perfectos para un look atlético y cómodo.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'pantalon',
    brand: 'Vanquish',
    fabric_type: '85% Algodón, 15% Polyester',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/vanquish/hombre/pantalones/jogger-tech.png', alt: 'Tech Joggers', dataAiHint: 'men joggers', option: 'M' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 5 }, { value: 'M', stock: 5 }, { value: 'L', stock: 5 }] },
  },
  {
    id: 400,
    name: 'Windbreaker Jacket',
    price: 'Q.700.00',
    availability: 'Disponible',
    description: 'Chamarra rompevientos ligera, ideal para protegerte del clima sin añadir peso.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'chamarra',
    brand: 'Darc Sport',
    fabric_type: '100% Polyester',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/darcsport/hombre/chamarras/chamarra-wind.png', alt: 'Windbreaker Jacket', dataAiHint: 'men jacket', option: 'M' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 5 }, { value: 'M', stock: 5 }, { value: 'L', stock: 5 }] },
  },
  {
    id: 500,
    name: 'Studio Crop Top',
    price: 'Q.380.00',
    availability: 'Disponible',
    description: 'Top corto versátil y cómodo, ideal para el estudio o para un look casual.',
    gender: 'mujer',
    category: 'ropa',
    subcategory: 'top',
    brand: 'Gymshark',
    fabric_type: '95% Cotton, 5% Elastane',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/gymshark/mujer/tops/top-studio.png', alt: "Women's Top", dataAiHint: 'woman top', option: 'M' }],
    options: { type: 'talla', values: [{ value: 'XS', stock: 5 }, { value: 'S', stock: 5 }, { value: 'M', stock: 5 }] },
  },
  {
    id: 700,
    name: 'Flex Legging',
    price: 'Q.550.00',
    availability: 'Disponible',
    description: 'Leggings flexibles que se mueven contigo. Diseño que realza la figura y no transparenta.',
    gender: 'mujer',
    category: 'ropa',
    subcategory: 'legging',
    brand: 'Gymshark',
    fabric_type: '87% Nylon, 13% Spandex',
    is_compression: true,
    images: [{ src: '/assets/images/marcas/gymshark/mujer/leggings/legging-flex.png', alt: 'Legging', dataAiHint: 'woman legging', option: 'M' }],
    options: { type: 'talla', values: [{ value: 'XS', stock: 5 }, { value: 'S', stock: 5 }, { value: 'M', stock: 5 }] },
  },
  {
    id: 1000,
    name: 'Cropped Jacket',
    price: 'Q.750.00',
    availability: 'Disponible',
    description: 'Chamarra corta moderna y funcional. Perfecta para combinar con tus leggings o tops favoritos.',
    gender: 'mujer',
    category: 'ropa',
    subcategory: 'chamarra',
    brand: 'Vanquish',
    fabric_type: '100% Polyester',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/vanquish/mujer/chamarras/chamarra-cropped.png', alt: "Women's Jacket", dataAiHint: 'woman jacket', option: 'M' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 5 }, { value: 'M', stock: 5 }, { value: 'L', stock: 5 }] },
  },
  {
    id: 1100,
    name: 'Hydrate Water Bottle',
    price: 'Q.150.00',
    availability: 'Disponible',
    description: 'Mantente hidratado con estilo. Botella de agua duradera y libre de BPA.',
    gender: 'unisex',
    category: 'accesorio',
    subcategory: 'pachon',
    brand: 'Generic',
    images: [{ src: '/assets/images/accesorios/pachones/pachon.png', alt: 'Water Bottle', dataAiHint: 'water bottle', option: 'Único' }],
    options: { type: 'color', values: [{ value: 'Único', stock: 10 }] },
  },
  {
    id: 1300,
    name: 'Training Gear',
    price: 'Q.250.00',
    availability: 'Disponible',
    description: 'Equipo esencial para tus entrenamientos, desde bandas de resistencia hasta cuerdas para saltar.',
    gender: 'unisex',
    category: 'accesorio',
    subcategory: 'equipo',
    brand: 'Generic',
    images: [{ src: '/assets/images/accesorios/equipo/equipo.png', alt: 'Training Gear', dataAiHint: 'gym gear', option: 'Único' }],
    options: { type: 'item', values: [{ value: 'Único', stock: 10 }] },
  },
  {
    id: 1400,
    name: 'Lifestyle Cap',
    price: 'Q.200.00',
    availability: 'Disponible',
    description: 'Completa tu look con esta gorra de estilo de vida. Ajustable y cómoda.',
    gender: 'unisex',
    category: 'accesorio',
    subcategory: 'gorra',
    brand: 'Generic',
    images: [{ src: '/assets/images/accesorios/gorras/gorra.png', alt: 'Cap', dataAiHint: 'fitness cap', option: 'Único' }],
    options: { type: 'color', values: [{ value: 'Único', stock: 10 }] },
  },
  {
    id: 1500,
    name: 'Gym Backpack',
    price: 'Q.500.00',
    availability: 'Disponible',
    description: 'Lleva todo tu equipo de gimnasio en esta mochila espaciosa y duradera.',
    gender: 'unisex',
    category: 'accesorio',
    subcategory: 'mochila',
    brand: 'Generic',
    images: [{ src: '/assets/images/accesorios/mochilas/mochila.png', alt: 'Backpack', dataAiHint: 'gym backpack', option: 'Único' }],
    options: { type: 'color', values: [{ value: 'Único', stock: 10 }] },
  },
  {
    id: 1600,
    name: 'Duffle Bag',
    price: 'Q.600.00',
    availability: 'Disponible',
    description: 'Maleta de gimnasio perfecta para viajes o para llevar todo lo que necesitas para entrenar.',
    gender: 'unisex',
    category: 'accesorio',
    subcategory: 'maleta',
    brand: 'Generic',
    images: [{ src: '/assets/images/accesorios/maletas/maleta.png', alt: 'Duffle Bag', dataAiHint: 'gym bag', option: 'Único' }],
    options: { type: 'color', values: [{ value: 'Único', stock: 10 }] },
  },
  {
    id: 1800,
    name: 'Whey Protein Isolate',
    price: 'Q.550.00',
    availability: 'Disponible',
    description: 'Proteína de suero de leche de alta calidad, perfecta para la recuperación post-entrenamiento.',
    gender: 'unisex',
    category: 'suplemento',
    subcategory: 'proteina',
    brand: 'Dragon Pharma',
    benefits: 'Apoya el crecimiento muscular, rápida absorción.',
    servings_info: '30 servicios por envase.',
    images: [{ src: '/assets/images/suplementos/proteinas/proteina.png', alt: 'Protein', dataAiHint: 'protein supplement', option: 'Vainilla' }],
    options: { type: 'sabor', values: [{ value: 'Vainilla', stock: 10 }, { value: 'Chocolate', stock: 10 }] },
  },
  {
    id: 1900,
    name: 'Micronized Creatine',
    price: 'Q.250.00',
    availability: 'Disponible',
    description: 'Aumenta tu fuerza y potencia con nuestra creatina micronizada de alta pureza.',
    gender: 'unisex',
    category: 'suplemento',
    subcategory: 'creatina',
    brand: 'RAW',
    benefits: 'Mejora el rendimiento, aumenta la fuerza.',
    servings_info: '100 servicios por envase.',
    images: [{ src: '/assets/images/suplementos/creatinas/creatina.png', alt: 'Creatine', dataAiHint: 'creatine supplement', option: 'Único' }],
    options: { type: 'tamaño', values: [{ value: '500g', stock: 10 }] },
  },
  {
    id: 2000,
    name: 'Explosive Pre-Workout',
    price: 'Q.400.00',
    availability: 'Disponible',
    description: 'Obtén la energía y el enfoque que necesitas para tus entrenamientos más intensos.',
    gender: 'unisex',
    category: 'suplemento',
    subcategory: 'pre-entreno',
    brand: 'C4 Energy',
    benefits: 'Aumenta la energía y el enfoque, mejora la resistencia.',
    servings_info: '30 servicios por envase.',
    images: [{ src: '/assets/images/suplementos/pre-entrenos/pre-entreno.png', alt: 'Pre-Workout', dataAiHint: 'pre-workout supplement', option: 'Fruit Punch' }],
    options: { type: 'sabor', values: [{ value: 'Fruit Punch', stock: 10 }, { value: 'Blue Raspberry', stock: 10 }] },
  },
  {
    id: 2100,
    name: 'BCAA 2:1:1',
    price: 'Q.350.00',
    availability: 'Disponible',
    description: 'Aminoácidos de cadena ramificada para apoyar la recuperación y reducir el dolor muscular.',
    gender: 'unisex',
    category: 'suplemento',
    subcategory: 'aminoacidos',
    brand: 'Dragon Pharma',
    benefits: 'Mejora la recuperación, reduce la fatiga muscular.',
    servings_info: '40 servicios por envase.',
    images: [{ src: '/assets/images/suplementos/aminoacidos/aminoacidos.png', alt: 'BCAA', dataAiHint: 'bcaa supplement', option: 'Watermelon' }],
    options: { type: 'sabor', values: [{ value: 'Watermelon', stock: 10 }, { value: 'Grape', stock: 10 }] },
  },
  {
    id: 2200,
    name: 'L-Carnitine Liquid',
    price: 'Q.300.00',
    availability: 'Disponible',
    description: 'Fórmula líquida de L-Carnitina para ayudar a convertir la grasa en energía.',
    gender: 'unisex',
    category: 'suplemento',
    subcategory: 'l-carnitina',
    brand: 'RAW',
    benefits: 'Apoya el metabolismo de las grasas, mejora la energía.',
    servings_info: '32 servicios por envase.',
    images: [{ src: '/assets/images/suplementos/l-carnitina/lcarnitina.png', alt: 'L-Carnitine', dataAiHint: 'l-carnitine supplement', option: 'Cherry' }],
    options: { type: 'sabor', values: [{ value: 'Cherry', stock: 10 }, { value: 'Orange', stock: 10 }] },
  },
  {
    id: 2300,
    name: 'Trident Pendant - Gold 14K SS "22.5"',
    price: 'Q.475.00',
    availability: 'Disponible',
    description: 'Eleva tu estilo con este colgante exclusivo de RGMNT. Hecho con materiales de primera calidad para un look audaz y duradero.',
    gender: 'unisex',
    category: 'joyeria',
    subcategory: 'rgmnt',
    brand: 'RGMNT',
    images: [{ src: '/assets/images/marcas/rgmnt/tridente.png', alt: 'Jewelry', dataAiHint: 'men jewelry', option: 'Gold' }],
    options: { type: 'material', values: [{ value: 'Gold', stock: 5 }] },
  },
  {
    id: 2400,
    name: 'Stealth Performance Tee',
    price: 'Q.420.00',
    availability: 'Disponible',
    description: 'Playera de rendimiento con tejido que absorbe la humedad para mantenerte seco y cómodo.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'Vanquish',
    fabric_type: '90% Polyester, 10% Elastane',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/vanquish/hombre/playeras/playera-stealth.png', alt: 'Stealth Performance Tee', dataAiHint: 'men shirt', option: 'M' }],
    options: { type: 'talla', values: [{ value: 'M', stock: 10 }, { value: 'L', stock: 8 }] },
  },
  {
    id: 2401,
    name: 'Wolves Club Tee',
    price: 'Q.480.00',
    availability: 'Disponible',
    description: 'Únete a la manada con esta exclusiva playera del "Wolves Club".',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'Darc Sport',
    fabric_type: '100% Algodón grueso',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/darcsport/hombre/playeras/playera-wolves.png', alt: 'Wolves Club Tee', dataAiHint: 'men shirt', option: 'XL' }],
    options: { type: 'talla', values: [{ value: 'L', stock: 10 }, { value: 'XL', stock: 5 }] },
  },
  {
    id: 2402,
    name: 'Apex Seamless T-Shirt',
    price: 'Q.510.00',
    availability: 'Disponible',
    description: 'Diseño sin costuras para una máxima comodidad y cero distracciones durante tu entrenamiento.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'Gymshark',
    fabric_type: '70% Polyester, 30% Nylon',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/gymshark/hombre/playeras/playera-apex.png', alt: 'Apex Seamless T-Shirt', dataAiHint: 'men shirt', option: 'M' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 9 }, { value: 'M', stock: 11 }] },
  },
  {
    id: 2403,
    name: 'Classic Logo Tee',
    price: 'Q.390.00',
    availability: 'Disponible',
    description: 'Una playera clásica con el icónico logo de la marca. Versátil y cómoda para el uso diario.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'YoungLA',
    fabric_type: '100% Algodón peinado',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/youngla/hombre/playeras/playera-classic.png', alt: 'Classic Logo Tee', dataAiHint: 'men shirt', option: 'S' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 15 }, { value: 'M', stock: 15 }, { value: 'L', stock: 10 }] },
  },
  {
    id: 2404,
    name: 'Arrival Athletic T-Shirt',
    price: 'Q.460.00',
    availability: 'Disponible',
    description: 'Playera atlética ligera con un ajuste que realza la figura. Ideal para cualquier actividad.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'Gymshark',
    fabric_type: '88% Polyester, 12% Elastane',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/gymshark/hombre/playeras/playera-arrival.png', alt: 'Arrival Athletic T-Shirt', dataAiHint: 'men shirt', option: 'M' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 8 }, { value: 'M', stock: 12 }, { value: 'L', stock: 9 }] },
  },
  {
    id: 2405,
    name: 'Core Training Tee',
    price: 'Q.400.00',
    availability: 'Disponible',
    description: 'La playera esencial para tu guardarropa de entrenamiento. Simple, funcional y duradera.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'Vanquish',
    fabric_type: '60% Algodón, 40% Polyester',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/vanquish/hombre/playeras/playera-core.png', alt: 'Core Training Tee', dataAiHint: 'men shirt', option: 'L' }],
    options: { type: 'talla', values: [{ value: 'M', stock: 20 }, { value: 'L', stock: 18 }] },
  },
  {
    id: 2501,
    name: '437 Digital Compression Tees',
    price: 'Q.325.00',
    availability: 'Disponible',
    description: 'Playera de compresión con diseño digital. Rendimiento y estilo en una sola prenda.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'YoungLA',
    fabric_type: '88% Polyester, 12% Spandex',
    is_compression: true,
    images: [{ src: '/assets/images/marcas/youngla/hombre/437 Digital Compression Tees Roja.png', alt: '437 Digital Compression Tees', dataAiHint: 'men shirt', option: 'Rojo' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2502,
    name: '425 Camiseta de compresión',
    price: 'Q.376.00',
    availability: 'Disponible',
    description: 'Camiseta de compresión diseñada para ofrecer soporte muscular y comodidad.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'YoungLA',
    fabric_type: '88% Polyester, 12% Spandex',
    is_compression: true,
    images: [{ src: '/assets/images/marcas/youngla/hombre/camisetadecomprecion.png', alt: '425 Camiseta de compresión', dataAiHint: 'men shirt', option: 'Verde' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2503,
    name: 'Elite Tees',
    price: 'Q.400.00',
    availability: 'Disponible',
    description: 'Playera de élite para un rendimiento superior.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'YoungLA',
    fabric_type: '95% Cotton, 5% Spandex',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/youngla/hombre/403 Elite Tees AZUL.png', alt: 'Elite Tees', dataAiHint: 'men shirt', option: 'S' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2504,
    name: '4096 - The Boys® Graphic Tees',
    price: 'Q.450.00',
    availability: 'Disponible',
    description: 'Playera con gráfico de The Boys®, edición Billy Butcher.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'YoungLA',
    fabric_type: '100% Cotton',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/youngla/hombre/4095 - The Boys® Graphic Tees.png', alt: '4096 - The Boys® Graphic Tees', dataAiHint: 'men shirt', option: 'Billy Butcher' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2505,
    name: '4207 - UFC™ Jersey',
    price: 'Q.445.00',
    availability: 'Disponible',
    description: 'Jersey oficial de la UFC™ para un look auténtico.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'YoungLA',
    fabric_type: '100% Polyester',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/youngla/hombre/4207 - UFC™ Jersey GRIS.png', alt: '4207 - UFC™ Jersey', dataAiHint: 'men jersey', option: 'Gris/negro' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2506,
    name: '477 Camiseta Compresion combat',
    price: 'Q.316.00',
    availability: 'Disponible',
    description: 'Camiseta de compresión para combate, máxima resistencia y flexibilidad.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'YoungLA',
    fabric_type: '88% Polyester, 12% Spandex',
    is_compression: true,
    images: [{ src: '/assets/images/marcas/youngla/hombre/477 Camiseta Comprecion combat NEGRO.png', alt: '477 Camiseta Compresion combat', dataAiHint: 'men shirt', option: 'Negro' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 20 }] },
  },
  {
    id: 2508,
    name: 'W237 On-The-Go Flare Romper',
    price: 'Q.500.00',
    availability: 'Disponible',
    description: 'Romper cómodo y estilizado para un look casual y activo.',
    gender: 'mujer',
    category: 'ropa',
    subcategory: 'top',
    brand: 'YoungLA',
    fabric_type: '95% Cotton, 5% Elastane',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/youngla/mujer/W237 On-The-Go Flare Romper NEGRO.png', alt: 'W237 On-The-Go Flare Romper', dataAiHint: 'woman romper', option: 'Negro' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2509,
    name: '5003 - UFC™ Cut-Off hoodies',
    price: 'Q.496.00',
    availability: 'Disponible',
    description: 'Sudadera sin mangas de la UFC™ para un estilo rudo y cómodo.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'sudadera',
    brand: 'YoungLA',
    fabric_type: '80% Cotton, 20% Polyester',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/youngla/hombre/5003 - UFC™ Cut-Off hoodies ROJO.png', alt: '5003 - UFC™ Cut-Off hoodies', dataAiHint: 'men hoodie', option: 'Rojo' }],
    options: { type: 'talla', values: [{ value: 'M', stock: 10 }] },
  },
  {
    id: 2510,
    name: '3002 GRAND SLAM BASEBALL JERSEYS',
    price: 'Q.405.00',
    availability: 'Disponible',
    description: 'Jersey de béisbol con estilo clásico y deportivo.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'YoungLA',
    fabric_type: '100% Polyester',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/youngla/hombre/3002 GRAND SLAM BASEBALL JERSEYS NEGRO.png', alt: '3002 GRAND SLAM BASEBALL JERSEYS', dataAiHint: 'men jersey', option: 'Negro' }],
    options: { type: 'talla', values: [{ value: 'M', stock: 10 }] },
  },
  {
    id: 2511,
    name: '4156 - Revenge Tees',
    price: 'Q.395.00',
    availability: 'Disponible',
    description: 'Playera con un diseño de venganza, para un look atrevido.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'YoungLA',
    fabric_type: '100% Cotton',
    is_compression: false,
    images: [
        { src: '/assets/images/marcas/youngla/hombre/4156 - Revenge Tees Negro.png', alt: '4156 - Revenge Tees Negro', dataAiHint: 'men shirt', option: 'Negro' }
    ],
    options: { type: 'talla', values: [{ value: 'M', stock: 10 }, { value: 'S', stock: 10 }] },
  },
  {
    id: 2513,
    name: '5092 - Effortless Sets',
    price: 'Q.370.00',
    availability: 'Disponible',
    description: 'Conjunto cómodo y sin esfuerzo para un look relajado.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'sudadera',
    brand: 'YoungLA',
    fabric_type: '95% Cotton, 5% Elastane',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/youngla/hombre/5092 - Effortless Sets NEGRO.png', alt: '5092 - Effortless Sets', dataAiHint: 'men set', option: 'Negro' }],
    options: { type: 'talla', values: [{ value: 'M', stock: 10 }] },
  },
  {
    id: 2514,
    name: '3005 - The Boys® Cut-Offs',
    price: 'Q.430.00',
    availability: 'Disponible',
    description: 'Playera sin mangas de The Boys®, edición Homelander.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'tank',
    brand: 'YoungLA',
    fabric_type: '100% Cotton',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/youngla/hombre/3005 - The Boys® Cut-Offs.png', alt: '3005 - The Boys® Cut-Offs', dataAiHint: 'men tank', option: 'Homelander Art' }],
    options: { type: 'talla', values: [{ value: 'M', stock: 10 }] },
  },
  {
    id: 2515,
    name: '477 - Combat Compression Tees',
    price: 'Q.315.00',
    availability: 'Disponible',
    description: 'Playera de compresión para combate, diseñada para el máximo rendimiento.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'YoungLA',
    fabric_type: '88% Polyester, 12% Spandex',
    is_compression: true,
    images: [{ src: '/assets/images/marcas/youngla/hombre/478 - Combat Compression Tees AZUL.png', alt: '477 - Combat Compression Tees', dataAiHint: 'men shirt', option: 'Azul' }],
    options: { type: 'talla', values: [{ value: 'M', stock: 10 }] },
  },
  {
    id: 2517,
    name: 'Vanquish Unconquerable Shorts',
    price: 'Q.345.00',
    availability: 'Disponible',
    description: 'Shorts inconquistables para tus entrenamientos más duros.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'short',
    brand: 'Vanquish',
    fabric_type: '90% Polyester, 10% Spandex',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/vanquish/vanquish/Vanquish Unconquerable Shorts NEGRO.png', alt: 'Vanquish Unconquerable Shorts', dataAiHint: 'men shorts', option: 'Negro' }],
    options: { type: 'talla', values: [{ value: 'M', stock: 10 }] },
  },
  {
    id: 2518,
    name: 'Lifting Club Apparel Graphic Shorts',
    price: 'Q.245.00',
    availability: 'Disponible',
    description: 'Shorts con gráfico del Lifting Club, perfectos para mostrar tu pasión.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'short',
    brand: 'Gymshark',
    fabric_type: '100% Cotton',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/gymshark/hombre/Lifting Club Apparel Graphic Shorts NEGRO.png', alt: 'Lifting Club Apparel Graphic Shorts', dataAiHint: 'men shorts', option: 'Negro' }],
    options: { type: 'talla', values: [{ value: 'XL', stock: 10 }] },
  },
  {
    id: 2519,
    name: 'Legacy Logo Tight Shorts',
    price: 'Q.340.00',
    availability: 'Disponible',
    description: 'Shorts ajustados con el logo Legacy para un look clásico y atlético.',
    gender: 'mujer',
    category: 'ropa',
    subcategory: 'short',
    brand: 'Gymshark',
    fabric_type: '87% Nylon, 13% Spandex',
    is_compression: true,
    images: [{ src: '/assets/images/marcas/gymshark/mujer/Legacy Logo Tight Shorts NEGRO.png', alt: 'Legacy Logo Tight Shorts', dataAiHint: 'woman shorts', option: 'Negro' }],
    options: { type: 'talla', values: [{ value: 'M', stock: 10 }] },
  },
  {
    id: 2520,
    name: 'Legacy Bra',
    price: 'Q.245.00',
    availability: 'Disponible',
    description: 'Bra deportivo Legacy para un soporte y estilo inigualables.',
    gender: 'mujer',
    category: 'ropa',
    subcategory: 'bra-deportivo',
    brand: 'Gymshark',
    fabric_type: '87% Nylon, 13% Spandex',
    is_compression: true,
    images: [{ src: '/assets/images/marcas/gymshark/mujer/legacy bra negro.png', alt: 'Legacy Bra', dataAiHint: 'sports bra', option: 'Negro' }],
    options: { type: 'talla', values: [{ value: 'M', stock: 10 }] },
  },
  {
    id: 2521,
    name: 'Rest Day Essentials Cargo Joggers',
    price: 'Q.411.00',
    availability: 'Disponible',
    description: 'Joggers cargo esenciales para tus días de descanso, comodidad y estilo.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'pantalon',
    brand: 'Gymshark',
    fabric_type: '100% Cotton',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/gymshark/hombre/Rest Day Essentials Cargo Joggers negro.png', alt: 'Rest Day Essentials Cargo Joggers', dataAiHint: 'men joggers', option: 'Negro' }],
    options: { type: 'talla', values: [{ value: 'M', stock: 10 }] },
  },
  {
    id: 2522,
    name: 'Strength Dept Graphic T-Shirt',
    price: 'Q.255.00',
    availability: 'Disponible',
    description: 'Playera con gráfico del departamento de fuerza, para los más fuertes.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'Gymshark',
    fabric_type: '100% Cotton',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/gymshark/hombre/Strength Dept Graphic T-Shirt blanca.png', alt: 'Strength Dept Graphic T-Shirt', dataAiHint: 'men shirt', option: 'Blanco' }],
    options: { type: 'talla', values: [{ value: 'M', stock: 10 }] },
  },
  {
    id: 2523,
    name: 'Flex Shorts (Blue)',
    price: 'Q.345.00',
    availability: 'Disponible',
    description: 'Shorts Flex para máxima flexibilidad y comodidad.',
    gender: 'mujer',
    category: 'ropa',
    subcategory: 'short',
    brand: 'Gymshark',
    fabric_type: '87% Nylon, 13% Spandex',
    is_compression: true,
    images: [{ src: '/assets/images/marcas/gymshark/mujer/Flex Shorts azul.png', alt: 'Flex Shorts', dataAiHint: 'woman shorts', option: 'Azul' }],
    options: { type: 'talla', values: [{ value: 'M', stock: 10 }] },
  },
  {
    id: 2524,
    name: 'Crop Top Flex',
    price: 'Q.336.00',
    availability: 'Disponible',
    description: 'Crop top de la línea Flex para un ajuste perfecto y cómodo.',
    gender: 'mujer',
    category: 'ropa',
    subcategory: 'top',
    brand: 'Gymshark',
    fabric_type: '87% Nylon, 13% Spandex',
    is_compression: true,
    images: [{ src: '/assets/images/marcas/gymshark/mujer/Crop Top Flex negro.png', alt: 'Crop Top Flex', dataAiHint: 'woman top', option: 'Negro' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2525,
    name: 'Power Oversized Long Sleeve Top',
    price: 'Q.280.00',
    availability: 'Disponible',
    description: 'Top de manga larga oversized para un look potente y relajado.',
    gender: 'mujer',
    category: 'ropa',
    subcategory: 'top',
    brand: 'Gymshark',
    fabric_type: '100% Cotton',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/gymshark/mujer/Power Oversized Long Sleeve Top negro.png', alt: 'Power Oversized Long Sleeve Top', dataAiHint: 'woman top', option: 'Negro' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2526,
    name: 'Legacy Hoodie',
    price: 'Q.280.00',
    availability: 'Disponible',
    description: 'Sudadera con capucha Legacy, un clásico que no puede faltar en tu armario.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'sudadera',
    brand: 'Gymshark',
    fabric_type: '80% Cotton, 20% Polyester',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/gymshark/hombre/Legacy Hoodie negra.png', alt: 'Legacy Hoodie', dataAiHint: 'men hoodie', option: 'Negro' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2527,
    name: 'Strength Department Graphic Joggers',
    price: 'Q.345.00',
    availability: 'Disponible',
    description: 'Joggers con gráfico del departamento de fuerza para un look completo.',
    gender: 'mujer',
    category: 'ropa',
    subcategory: 'pantalon',
    brand: 'Gymshark',
    fabric_type: '100% Cotton',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/gymshark/mujer/Strength Department Graphic Joggers negro.png', alt: 'Strength Department Graphic Joggers', dataAiHint: 'woman joggers', option: 'Negro' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2528,
    name: 'Sets N Reps T-Shirt',
    price: 'Q.380.00',
    availability: 'Disponible',
    description: 'Playera para tus series y repeticiones, cómoda y resistente.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'Gymshark',
    fabric_type: '100% Cotton',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/gymshark/hombre/Sets N Reps T-Shirt verde.png', alt: 'Sets N Reps T-Shirt', dataAiHint: 'men shirt', option: 'Verde' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2529,
    name: 'Lightweight Jersey Shorts',
    price: 'Q.256.00',
    availability: 'Disponible',
    description: 'Shorts de jersey ligeros para una comodidad y movilidad excepcionales.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'short',
    brand: 'Gymshark',
    fabric_type: '100% Cotton',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/gymshark/hombre/Lightweight Jersey Shorts azul.png', alt: 'Lightweight Jersey Shorts', dataAiHint: 'men shorts', option: 'Azul' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2530,
    name: 'British Lifting Goods Graphic T-Shirt',
    price: 'Q.285.00',
    availability: 'Disponible',
    description: 'Playera con gráfico de British Lifting Goods, para un estilo clásico.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'Gymshark',
    fabric_type: '100% Cotton',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/gymshark/hombre/Built in the UK T-Shirt azul.png', alt: 'British Lifting Goods Graphic T-Shirt', dataAiHint: 'men shirt', option: 'Azul' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2531,
    name: 'Crest 7" Shorts',
    price: 'Q.296.00',
    availability: 'Disponible',
    description: 'Shorts de 7 pulgadas de la línea Crest, perfectos para cualquier actividad.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'short',
    brand: 'Gymshark',
    fabric_type: '80% Cotton, 20% Polyester',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/gymshark/hombre/Crest 7 Shorts gris.png', alt: 'Crest 7" Shorts', dataAiHint: 'men shorts', option: 'Gris' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2532,
    name: 'Built in the UK T-Shirt',
    price: 'Q.240.00',
    availability: 'Disponible',
    description: 'Playera con gráfico "Built in the UK", un clásico de la marca.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'Gymshark',
    fabric_type: '100% Cotton',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/gymshark/hombre/Built in the UK T-Shirt azul.png', alt: 'Built in the UK T-Shirt', dataAiHint: 'men shirt', option: 'Azul' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2533,
    name: 'Ribbed Tank 3 Pack',
    price: 'Q.395.00',
    availability: 'Disponible',
    description: 'Paquete de 3 tanques acanalados para tus entrenamientos diarios.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'tank',
    brand: 'Gymshark',
    fabric_type: '100% Cotton',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/gymshark/hombre/Ribbed Tank 3 Pack gris.png', alt: 'Ribbed Tank 3 Pack', dataAiHint: 'men tank', option: 'Gris' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2534,
    name: 'Element Long Sleeve T-Shirt',
    price: 'Q.340.00',
    availability: 'Disponible',
    description: 'Playera de manga larga de la línea Element, ligera y cómoda.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'Gymshark',
    fabric_type: '88% Polyester, 12% Elastane',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/gymshark/hombre/Element Long Sleeve T-Shirt negra y rojo.png', alt: 'Element Long Sleeve T-Shirt', dataAiHint: 'men shirt', option: 'Negro' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2535,
    name: 'Adapt Fleck Sports Bra',
    price: 'Q.446.00',
    availability: 'Disponible',
    description: 'Bra deportivo de la línea Adapt Fleck para un ajuste y soporte perfectos.',
    gender: 'mujer',
    category: 'ropa',
    subcategory: 'bra-deportivo',
    brand: 'Gymshark',
    fabric_type: '79% Nylon, 15% Polyester, 6% Elastane',
    is_compression: true,
    images: [{ src: '/assets/images/marcas/gymshark/mujer/Adapt Fleck Sports Bra morado.png', alt: 'Adapt Fleck Sports Bra', dataAiHint: 'sports bra', option: 'Morado' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2536,
    name: 'Adapt Fleck Seamless Shorts',
    price: 'Q.400.00',
    availability: 'Disponible',
    description: 'Shorts sin costuras de la línea Adapt Fleck para un confort inigualable.',
    gender: 'mujer',
    category: 'ropa',
    subcategory: 'short',
    brand: 'Gymshark',
    fabric_type: '79% Nylon, 15% Polyester, 6% Elastane',
    is_compression: true,
    images: [{ src: '/assets/images/marcas/gymshark/mujer/Adapt Fleck Seamless Shorts morado.png', alt: 'Adapt Fleck Seamless Shorts', dataAiHint: 'woman shorts', option: 'Morado' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2538,
    name: 'Training Fleece Joggers',
    price: 'Q.375.00',
    availability: 'Disponible',
    description: 'Joggers de polar para entrenamiento, cálidos y cómodos.',
    gender: 'mujer',
    category: 'ropa',
    subcategory: 'pantalon',
    brand: 'Gymshark',
    fabric_type: '80% Cotton, 20% Polyester',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/gymshark/mujer/Training Fleece Joggers verde.png', alt: 'Training Fleece Joggers', dataAiHint: 'woman joggers', option: 'Verde' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2539,
    name: 'Mesh Sports Bra',
    price: 'Q.266.00',
    availability: 'Disponible',
    description: 'Bra deportivo con detalles de malla para mayor transpirabilidad.',
    gender: 'mujer',
    category: 'ropa',
    subcategory: 'bra-deportivo',
    brand: 'Gymshark',
    fabric_type: '88% Polyester, 12% Elastane',
    is_compression: true,
    images: [{ src: '/assets/images/marcas/gymshark/mujer/Mesh Sports Bra negro.png', alt: 'Mesh Sports Bra', dataAiHint: 'sports bra', option: 'Negro' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 20 }] },
  },
  {
    id: 2541,
    name: 'Ruched Sports Bra',
    price: 'Q.291.00',
    availability: 'Disponible',
    description: 'Bra deportivo con diseño fruncido para un estilo único.',
    gender: 'mujer',
    category: 'ropa',
    subcategory: 'bra-deportivo',
    brand: 'Gymshark',
    fabric_type: '87% Nylon, 13% Spandex',
    is_compression: true,
    images: [{ src: '/assets/images/marcas/gymshark/mujer/Ruched Sports Bra negro.png', alt: 'Ruched Sports Bra', dataAiHint: 'sports bra', option: 'Negro' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2542,
    name: 'Strap Feature Sports Bra',
    price: 'Q.285.00',
    availability: 'Disponible',
    description: 'Bra deportivo con tirantes decorativos para un look moderno.',
    gender: 'mujer',
    category: 'ropa',
    subcategory: 'bra-deportivo',
    brand: 'Gymshark',
    fabric_type: '87% Nylon, 13% Spandex',
    is_compression: true,
    images: [{ src: '/assets/images/marcas/gymshark/mujer/Strap Feature Sports Bra negro.png', alt: 'Strap Feature Sports Bra', dataAiHint: 'sports bra', option: 'negro' }],
    options: { type: 'talla', values: [{ value: 'M', stock: 10 }] },
  },
  {
    id: 2543,
    name: 'Flex Shorts (Black)',
    price: 'Q.270.00',
    availability: 'Disponible',
    description: 'Shorts Flex para máxima flexibilidad y comodidad.',
    gender: 'mujer',
    category: 'ropa',
    subcategory: 'short',
    brand: 'Gymshark',
    fabric_type: '87% Nylon, 13% Spandex',
    is_compression: true,
    images: [{ src: '/assets/images/marcas/gymshark/mujer/Flex Shorts azul.png', alt: 'Flex Shorts', dataAiHint: 'woman shorts', option: 'Negro' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2544,
    name: 'Elevate Cycling Shorts',
    price: 'Q.296.00',
    availability: 'Disponible',
    description: 'Shorts de ciclismo de la línea Elevate para un rendimiento superior.',
    gender: 'mujer',
    category: 'ropa',
    subcategory: 'short',
    brand: 'Gymshark',
    fabric_type: '78% Polyester, 22% Elastane',
    is_compression: true,
    images: [{ src: '/assets/images/marcas/gymshark/mujer/Elevate Cycling Shorts negro.png', alt: 'Elevate Cycling Shorts', dataAiHint: 'woman shorts', option: 'Negro' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2545,
    name: 'Ease Woven Joggers',
    price: 'Q.336.00',
    availability: 'Disponible',
    description: 'Joggers tejidos de la línea Ease para una comodidad insuperable.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'pantalon',
    brand: 'Gymshark',
    fabric_type: '100% Polyester',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/gymshark/hombre/Ease Woven Joggers gris.png', alt: 'Ease Woven Joggers', dataAiHint: 'men joggers', option: 'Gris' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2546,
    name: '2005 - Hella Pocket Sweats',
    price: 'Q.580.00',
    availability: 'Disponible',
    description: 'Pantalones de chándal con muchos bolsillos para un estilo urbano y funcional.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'pantalon',
    brand: 'YoungLA',
    fabric_type: '100% Cotton',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/youngla/hombre/2005 - Hella Pocket Sweats morado.png', alt: '2005 - Hella Pocket Sweats', dataAiHint: 'men pants', option: 'Deep Purple Wash' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2547,
    name: 'Premium Lifting T-Shirt',
    price: 'Q.265.00',
    availability: 'Disponible',
    description: 'Playera premium para levantamiento, diseñada para durar.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'Gymshark',
    fabric_type: '100% Cotton',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/gymshark/hombre/Premium Lifting T-Shirt beige.png', alt: 'Premium Lifting T-Shirt', dataAiHint: 'men shirt', option: 'Sand Brown' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2548,
    name: 'Through Fire And Storm "Premium" Oversized Tee in Wolf Gray',
    price: 'Q.435.00',
    availability: 'Disponible',
    description: 'Playera oversized premium con un diseño épico.',
    gender: 'hombre',
    category: 'ropa',
    subcategory: 'playera',
    brand: 'Darc Sport',
    fabric_type: '100% Cotton',
    is_compression: false,
    images: [{ src: '/assets/images/marcas/darcsport/Through Fire And Storm Premium Oversized Tee in Wolf Gray.png', alt: 'Through Fire And Storm "Premium" Oversized Tee', dataAiHint: 'men shirt', option: 'Black' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 10 }] },
  },
  {
    id: 2549,
    name: 'Silicone Lifting Straps',
    price: 'Q.275.00',
    availability: 'Disponible',
    description: 'Correas de levantamiento de silicona para un agarre seguro.',
    gender: 'unisex',
    category: 'accesorio',
    subcategory: 'equipo',
    brand: 'Gymshark',
    images: [{ src: '/assets/images/marcas/gymshark/hombre/siliconeliftingstraps.png', alt: 'Silicone Lifting Straps', dataAiHint: 'lifting straps', option: 'purpura' }],
    options: { type: 'color', values: [{ value: 'purpura', stock: 10 }] },
  },
  {
    id: 2550,
    name: 'SHARKHEAD CAP',
    price: 'Q.305.00',
    availability: 'Disponible',
    description: 'Gorra clásica con el logo de Sharkhead.',
    gender: 'unisex',
    category: 'accesorio',
    subcategory: 'gorra',
    brand: 'Gymshark',
    images: [{ src: '/assets/images/marcas/gymshark/hombre/sharkheadcap.png', alt: 'SHARKHEAD CAP', dataAiHint: 'fitness cap', option: 'Black' }],
    options: { type: 'color', values: [{ value: 'Black', stock: 3 }] },
  },
  {
    id: 2551,
    name: 'Crew Socks 3pk',
    price: 'Q.236.00',
    availability: 'Disponible',
    description: 'Paquete de 3 pares de calcetines.',
    gender: 'unisex',
    category: 'accesorio',
    subcategory: 'calcetin',
    brand: 'Gymshark',
    images: [
        { src: '/assets/images/marcas/gymshark/hombre/crewsocks3pk.png', alt: 'Crew Socks 3pk', dataAiHint: 'fitness socks', option: 'Mixto' }
    ],
    options: { type: 'color', values: [{ value: 'Mixto', stock: 10 }, { value: 'Blancos', stock: 10 }] },
  },
  {
    id: 2555,
    name: 'Sets N Reps 3pk Crew Socks',
    price: 'Q.251.00',
    availability: 'Disponible',
    description: 'Calcetines para tus series y repeticiones.',
    gender: 'unisex',
    category: 'accesorio',
    subcategory: 'calcetin',
    brand: 'Gymshark',
    images: [{ src: '/assets/images/accesorios/calcetines/calcetines-setsnreps.png', alt: 'Sets and Reps 3pk Crew Socks', dataAiHint: 'fitness socks', option: 'Sets' }],
    options: { type: 'talla', values: [{ value: 'S', stock: 20 }] },
  },
  {
    id: 2559,
    name: '933 YoungLA Keychains',
    price: 'Q.130.00',
    availability: 'Disponible',
    description: 'Llavero de YoungLA para llevar tu marca a todas partes.',
    gender: 'unisex',
    category: 'accesorio',
    subcategory: 'equipo',
    brand: 'YoungLA',
    images: [{ src: '/assets/images/accesorios/equipo/llavero-youngla.png', alt: '933 YoungLA Keychains', dataAiHint: 'keychain', option: 'Black' }],
    options: { type: 'color', values: [{ value: 'Black', stock: 20 }] },
  },
  {
    id: 2561,
    name: 'TU MARIDO MOISES SHAKER CUP',
    price: 'Q.170.00',
    availability: 'Disponible',
    description: 'Shaker exclusivo para tus batidos.',
    gender: 'unisex',
    category: 'accesorio',
    subcategory: 'shaker',
    brand: 'Dragon Pharma',
    images: [{ src: '/assets/images/marcas/dragonpharma/TU MARIDO MOISES SHAKER CUP.png', alt: 'TU MARIDO MOISES SHAKER CUP', dataAiHint: 'protein shaker', option: 'Black' }],
    options: { type: 'color', values: [{ value: 'Black', stock: 20 }] },
  },
  {
    id: 2563,
    name: 'CREATINE MONOHYDRATE ESSENTIALS 60 Servings',
    price: 'Q.325.00',
    availability: 'Disponible',
    description: 'Creatina monohidratada esencial para mejorar tu rendimiento.',
    gender: 'unisex',
    category: 'suplemento',
    subcategory: 'creatina',
    brand: 'Dragon Pharma',
    benefits: 'Aumento de fuerza y potencia.',
    servings_info: '60 servicios',
    images: [{ src: '/assets/images/suplementos/creatinas/creatina-essentials.png', alt: 'CREATINE MONOHYDRATE ESSENTIALS', dataAiHint: 'creatine supplement', option: 'Único' }],
    options: { type: 'presentacion', values: [{ value: 'Único', stock: 10 }] },
  },
  {
    id: 2564,
    name: 'GLUTAMINE',
    price: 'Q.345.00',
    availability: 'Disponible',
    description: 'Glutamina para una mejor recuperación muscular.',
    gender: 'unisex',
    category: 'suplemento',
    subcategory: 'aminoacidos',
    brand: 'Dragon Pharma',
    benefits: 'Mejora la recuperación y el sistema inmunológico.',
    servings_info: '60 servicios',
    images: [{ src: '/assets/images/marcas/dragonpharma/GLUTAMINE 30 SERVS.png', alt: 'GLUTAMINE', dataAiHint: 'glutamine supplement', option: 'Único' }],
    options: { type: 'presentacion', values: [{ value: 'Único', stock: 20 }] },
  },
  {
    id: 2566,
    name: 'DR. FEAAR® - Complete Essential Amino Acid Raspberry Lemonade',
    price: 'Q.350.00',
    availability: 'Disponible',
    description: 'Aminoácidos esenciales completos para una recuperación óptima.',
    gender: 'unisex',
    category: 'suplemento',
    subcategory: 'aminoacidos',
    brand: 'Dragon Pharma',
    benefits: 'Apoya la síntesis de proteínas y la recuperación.',
    servings_info: '30 servicios',
    images: [{ src: '/assets/images/marcas/dragonpharma/DR. FEAAR® - Complete Essential Amino Acid Raspberry Lemonade.png', alt: 'DR. FEAAR®', dataAiHint: 'amino acids', option: 'Raspberry Lemonade' }],
    options: { type: 'sabor', values: [{ value: 'Raspberry Lemonade', stock: 20 }] },
  },
  {
    id: 2568,
    name: 'GREENS & REDS',
    price: 'Q.485.00',
    availability: 'Disponible',
    description: 'Superalimentos verdes y rojos para tu bienestar general.',
    gender: 'unisex',
    category: 'suplemento',
    subcategory: 'proteina',
    brand: 'Dragon Pharma',
    benefits: 'Mejora la salud digestiva y el sistema inmunológico.',
    servings_info: '30 servicios',
    images: [{ src: '/assets/images/marcas/dragonpharma/GREENS & REDS.png', alt: 'GREENS & REDS', dataAiHint: 'greens supplement', option: 'Único' }],
    options: { type: 'presentacion', values: [{ value: 'Único', stock: 10 }] },
  },
  {
    id: 2569,
    name: 'VENOM INFERNO BRAZO DE 50 LIMÓN',
    price: 'Q.485.00',
    availability: 'Disponible',
    description: 'Pre-entreno potente para una energía explosiva.',
    gender: 'unisex',
    category: 'suplemento',
    subcategory: 'pre-entreno',
    brand: 'Dragon Pharma',
    benefits: 'Aumenta la energía, el enfoque y la resistencia.',
    servings_info: '50 servicios',
    images: [{ src: '/assets/images/marcas/dragonpharma/VENOM INFERNO BRAZO DE 50 LIMÓN.png', alt: 'VENOM INFERNO', dataAiHint: 'pre-workout', option: 'Limón' }],
    options: { type: 'sabor', values: [{ value: 'Limón', stock: 20 }] },
  },
  {
    id: 2571,
    name: 'Venom Mangonada',
    price: 'Q.530.00',
    availability: 'Disponible',
    description: 'Pre-entreno con sabor a mangonada para un entrenamiento intenso.',
    gender: 'unisex',
    category: 'suplemento',
    subcategory: 'pre-entreno',
    brand: 'Dragon Pharma',
    benefits: 'Energía explosiva y enfoque mental.',
    servings_info: '40 servicios',
    images: [{ src: '/assets/images/marcas/dragonpharma/Venom Mangonada.png', alt: 'Venom Mangonada', dataAiHint: 'pre-workout', option: 'Mangonada' }],
    options: { type: 'sabor', values: [{ value: 'Mangonada', stock: 10 }] },
  },
  {
    id: 2572,
    name: 'L-carnitina',
    price: 'Q.380.00',
    availability: 'Disponible',
    description: 'L-carnitina para ayudar a convertir la grasa en energía.',
    gender: 'unisex',
    category: 'suplemento',
    subcategory: 'l-carnitina',
    brand: 'Dragon Pharma',
    benefits: 'Apoya el metabolismo de las grasas.',
    servings_info: '60 servicios',
    images: [{ src: '/assets/images/marcas/dragonpharma/L-carnitina.png', alt: 'L-carnitina', dataAiHint: 'l-carnitine', option: 'Único' }],
    options: { type: 'presentacion', values: [{ value: 'Único', stock: 10 }] },
  },
  {
    id: 2574,
    name: 'BUM Essential pre-workout',
    price: 'Q.400.00',
    availability: 'Disponible',
    description: 'Pre-entreno esencial para un rendimiento óptimo, con el respaldo de Chris Bumstead.',
    gender: 'unisex',
    category: 'suplemento',
    subcategory: 'pre-entreno',
    brand: 'RAW',
    benefits: 'Energía sostenida, enfoque mejorado y bombeos musculares intensos.',
    servings_info: 'Aproximadamente 40 servicios.',
    images: [{ src: '/assets/images/marcas/raw/BUM Essential pre-workout thavage.png', alt: 'BUM Essential pre-workout', dataAiHint: 'pre-workout supplement', option: 'Liche' }],
    options: {
      type: 'sabor',
      values: [{ value: 'Liche', stock: 10 }],
    },
  }
];


